#!/bin/sh
set -eu

if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
  systemctl enable simaai-peripherals.service || true
  systemctl restart simaai-peripherals.service || true
fi

exit 0
