// Generated by tools/generate_sima_cvu_capability_abi.py; do not edit.
// Source SHA-256: 5d7636eee6695acf591da814604f98c5dead4c4d10f3b34cf1d94870211af2f5
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SIMA_CVU_CAPABILITY_SCHEMA_SHA256 "5d7636eee6695acf591da814604f98c5dead4c4d10f3b34cf1d94870211af2f5"
#define SIMA_CVU_CAPABILITY_ABI_VERSION UINT32_C(2)
#define SIMA_CVU_CAPABILITY_ABI_RECORD_COUNT UINT32_C(14)
#define SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1 UINT32_C(1)
#define SIMA_CVU_DESCRIPTOR_ABI_PREPROC_V1 UINT32_C(2)
#define SIMA_CVU_DESCRIPTOR_ABI_VISUAL_FRONTEND_V1 UINT32_C(3)
#define SIMA_CVU_PLACEMENT_EV74 (UINT32_C(1) << 0U)
#define SIMA_CVU_PLACEMENT_A65 (UINT32_C(1) << 1U)
#define SIMA_CVU_FRAME_PATCH_METADATA (UINT32_C(1) << 0U)
#define SIMA_CVU_FRAME_PATCH_PREPROC_GEOMETRY (UINT32_C(1) << 1U)
#define SIMA_CVU_FRAME_PATCH_PREPROC_SCALAR_ROI (UINT32_C(1) << 2U)
#define SIMA_CVU_FRAME_PATCH_PREPROC_ROI_LIST (UINT32_C(1) << 3U)
#define SIMA_CVU_FRAME_PATCH_PREPROC_PLANE_LAYOUT (UINT32_C(1) << 4U)
#define SIMA_CVU_SEMANTIC_OP_NONE UINT32_C(0)
#define SIMA_CVU_SEMANTIC_OP_CAST UINT32_C(1)
#define SIMA_CVU_SEMANTIC_OP_QUANTIZE UINT32_C(2)
#define SIMA_CVU_SEMANTIC_OP_TESSELLATE UINT32_C(3)
#define SIMA_CVU_SEMANTIC_OP_DETESSELLATE UINT32_C(4)
#define SIMA_CVU_SEMANTIC_OP_DEQUANTIZE UINT32_C(5)
#define SIMA_CVU_SEMANTIC_OP_PREPROC UINT32_C(6)
#define SIMA_CVU_SEMANTIC_OP_FEATURE_HISTOGRAM UINT32_C(7)
#define SIMA_CVU_SEMANTIC_OP_GRIDER_FAST UINT32_C(8)
#define SIMA_CVU_SEMANTIC_OP_TRACK_DESCRIPTOR UINT32_C(9)
#define SIMA_CVU_SEMANTIC_OP_TRACK_KLT UINT32_C(10)

/*
 * Fields: graph id, descriptor ABI, descriptor version, binding version,
 * placement mask, frame-patch mask, maximum members, canonical token,
 * ordered semantic-pattern length/op0/op1, mandatory-when-matched.
 */
#define SIMA_CVU_CAPABILITY_ABI_RECORDS(X) \
  X(2, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "tessellate", 1, SIMA_CVU_SEMANTIC_OP_TESSELLATE, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(3, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "detessellate", 1, SIMA_CVU_SEMANTIC_OP_DETESSELLATE, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(200, SIMA_CVU_DESCRIPTOR_ABI_PREPROC_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74), (SIMA_CVU_FRAME_PATCH_METADATA | SIMA_CVU_FRAME_PATCH_PREPROC_GEOMETRY | SIMA_CVU_FRAME_PATCH_PREPROC_SCALAR_ROI | SIMA_CVU_FRAME_PATCH_PREPROC_ROI_LIST | SIMA_CVU_FRAME_PATCH_PREPROC_PLANE_LAYOUT), 1, "preproc", 1, SIMA_CVU_SEMANTIC_OP_PREPROC, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(221, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "cast", 1, SIMA_CVU_SEMANTIC_OP_CAST, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(222, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "quantize", 1, SIMA_CVU_SEMANTIC_OP_QUANTIZE, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(223, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "dequantize", 1, SIMA_CVU_SEMANTIC_OP_DEQUANTIZE, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(224, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "casttess", 2, SIMA_CVU_SEMANTIC_OP_CAST, SIMA_CVU_SEMANTIC_OP_TESSELLATE, 1) \
  X(225, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "detesscast", 2, SIMA_CVU_SEMANTIC_OP_DETESSELLATE, SIMA_CVU_SEMANTIC_OP_CAST, 1) \
  X(226, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "quantizetessellate", 2, SIMA_CVU_SEMANTIC_OP_QUANTIZE, SIMA_CVU_SEMANTIC_OP_TESSELLATE, 1) \
  X(227, SIMA_CVU_DESCRIPTOR_ABI_TENSOR_TRANSFORM_PAIR_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74 | SIMA_CVU_PLACEMENT_A65), (SIMA_CVU_FRAME_PATCH_METADATA), 32, "detessdequant", 2, SIMA_CVU_SEMANTIC_OP_DETESSELLATE, SIMA_CVU_SEMANTIC_OP_DEQUANTIZE, 1) \
  X(235, SIMA_CVU_DESCRIPTOR_ABI_VISUAL_FRONTEND_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74), (SIMA_CVU_FRAME_PATCH_METADATA), 1, "feature_histogram", 1, SIMA_CVU_SEMANTIC_OP_FEATURE_HISTOGRAM, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(236, SIMA_CVU_DESCRIPTOR_ABI_VISUAL_FRONTEND_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74), (SIMA_CVU_FRAME_PATCH_METADATA), 1, "grider_fast", 1, SIMA_CVU_SEMANTIC_OP_GRIDER_FAST, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(237, SIMA_CVU_DESCRIPTOR_ABI_VISUAL_FRONTEND_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74), (SIMA_CVU_FRAME_PATCH_METADATA), 1, "track_descriptor", 1, SIMA_CVU_SEMANTIC_OP_TRACK_DESCRIPTOR, SIMA_CVU_SEMANTIC_OP_NONE, 0) \
  X(238, SIMA_CVU_DESCRIPTOR_ABI_VISUAL_FRONTEND_V1, 1, 1, (SIMA_CVU_PLACEMENT_EV74), (SIMA_CVU_FRAME_PATCH_METADATA), 1, "track_klt", 1, SIMA_CVU_SEMANTIC_OP_TRACK_KLT, SIMA_CVU_SEMANTIC_OP_NONE, 0)

typedef struct SimaCvuCapabilityAbiRecord {
  uint32_t graph_id;
  uint32_t descriptor_abi_id;
  uint32_t descriptor_contract_version;
  uint32_t binding_schema_version;
  uint32_t supported_placement_mask;
  uint32_t allowed_frame_patch_mask;
  uint32_t maximum_members;
  const char* canonical_token;
  uint32_t semantic_pattern_length;
  uint32_t semantic_op0;
  uint32_t semantic_op1;
  uint32_t mandatory_when_matched;
} SimaCvuCapabilityAbiRecord;

static inline const SimaCvuCapabilityAbiRecord*
sima_cvu_capability_abi_records(uint32_t* count) {
#define SIMA_CVU_CAPABILITY_INITIALIZER(\
    id, abi, version, binding, placement, patches, maximum, token, \
    pattern_length, op0, op1, mandatory) \
  {UINT32_C(id), (uint32_t)(abi), UINT32_C(version), UINT32_C(binding), \
   (uint32_t)(placement), (uint32_t)(patches), UINT32_C(maximum), token, \
   UINT32_C(pattern_length), (uint32_t)(op0), (uint32_t)(op1), \
   UINT32_C(mandatory)},
  static const SimaCvuCapabilityAbiRecord kRecords[] = {
      SIMA_CVU_CAPABILITY_ABI_RECORDS(SIMA_CVU_CAPABILITY_INITIALIZER)};
#undef SIMA_CVU_CAPABILITY_INITIALIZER
  if (count) {
    *count = SIMA_CVU_CAPABILITY_ABI_RECORD_COUNT;
  }
  return kRecords;
}

static inline int sima_cvu_capability_abi_lookup(
    uint32_t graph_id, SimaCvuCapabilityAbiRecord* out) {
  uint32_t count;
  uint32_t index;
  const SimaCvuCapabilityAbiRecord* records =
      sima_cvu_capability_abi_records(&count);
  for (index = 0; index < count; ++index) {
    if (records[index].graph_id == graph_id) {
      if (out) {
        *out = records[index];
      }
      return 1;
    }
  }
  return 0;
}

static inline int sima_cvu_capability_abi_lookup_semantic_pattern(
    uint32_t pattern_length, uint32_t op0, uint32_t op1,
    SimaCvuCapabilityAbiRecord* out) {
  uint32_t count;
  uint32_t index;
  const SimaCvuCapabilityAbiRecord* records =
      sima_cvu_capability_abi_records(&count);
  for (index = 0; index < count; ++index) {
    if (records[index].semantic_pattern_length == pattern_length &&
        records[index].semantic_op0 == op0 &&
        records[index].semantic_op1 == op1) {
      if (out) {
        *out = records[index];
      }
      return 1;
    }
  }
  return 0;
}

#ifdef __cplusplus
}
#endif
