#!/usr/bin/env python3
"""Generate platform-version artifacts for C++ and Python consumers.

Source of truth: deps/manifest.json (field: platform-version)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def _load_platform_version(manifest_path: Path) -> str:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    version = str(data.get("platform-version", "")).strip()
    if not version:
        raise ValueError(f"Missing or empty 'platform-version' in {manifest_path}")
    return version


def _write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def _render_cpp_header(version: str) -> str:
    return (
        "#pragma once\n\n"
        "// Auto-generated by tools/generate_platform_version_artifacts.py\n"
        "namespace sima_generated {\n"
        f"inline constexpr const char* kPlatformVersion = \"{version}\";\n"
        "} // namespace sima_generated\n"
    )


def _render_python_module(version: str) -> str:
    return (
        "\"\"\"Auto-generated by tools/generate_platform_version_artifacts.py.\"\"\"\n"
        f"PLATFORM_VERSION = \"{version}\"\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--manifest",
        type=Path,
        help="Path to deps manifest.json (default: <repo-root>/deps/manifest.json)",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    manifest_path = (args.manifest or (repo_root / "deps" / "manifest.json")).resolve()
    version = _load_platform_version(manifest_path)

    cpp_header_path = repo_root / "generated" / "platform_version.h"
    py_module_path = repo_root / "python" / "tests" / "_platform_version_generated.py"

    _write_if_changed(cpp_header_path, _render_cpp_header(version))
    _write_if_changed(py_module_path, _render_python_module(version))

    print(f"Generated platform version artifacts from {manifest_path}: {version}")
    print(f"  - {cpp_header_path}")
    print(f"  - {py_module_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
