#!/usr/bin/env python3
"""Generate the fail-closed C++ AFE publication ledger from release JSON."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def render(source: Path) -> str:
    data = json.loads(source.read_text())
    if data != {"schema": data.get("schema"), "version": data.get("version"),
                "contracts": data.get("contracts")}:
        raise ValueError("ledger has unknown top-level fields")
    if data["schema"] != "sima.neat.afe-publication-ledger" or data["version"] != 1:
        raise ValueError("unsupported publication ledger schema/version")
    contracts = data["contracts"]
    if not isinstance(contracts, list) or not contracts:
        raise ValueError("publication ledger must contain contracts")
    lines = ["// Generated by tools/generate_afe_publication_ledger.py; do not edit.", ""]
    records = []
    seen = set()
    for index, item in enumerate(contracts):
        if set(item) != {"model", "mpk_json_sha256", "ordered_outputs"}:
            raise ValueError(f"contract {index} has unknown or missing fields")
        digest = item["mpk_json_sha256"]
        outputs = item["ordered_outputs"]
        if not re.fullmatch(r"[0-9a-f]{64}", digest) or digest in seen:
            raise ValueError(f"contract {index} has invalid/duplicate digest")
        if not isinstance(outputs, list) or not outputs or len(set(outputs)) != len(outputs):
            raise ValueError(f"contract {index} has invalid outputs")
        seen.add(digest)
        name = f"kPublicationOutputs{index}"
        lines.append(f"constexpr std::array<std::string_view, {len(outputs)}> {name}{{{{")
        lines.extend(f"    {json.dumps(value)}," for value in outputs)
        lines.append("}};")
        records.append((digest, name))
    lines.append("")
    lines.append(
        f"constexpr std::array<AfePublicationContract, {len(records)}> "
        "kGeneratedPublicationContracts{{")
    lines.extend(f'    AfePublicationContract{{"{digest}", {name}}},' for digest, name in records)
    lines.append("}};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(args.source)
    if args.check:
        if not args.output.exists() or args.output.read_text() != rendered:
            raise SystemExit("generated publication ledger is stale")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
