/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Mirror the hardware docs sidebar: a titled lead item, then the section
  // tree. The sections are auto-generated from the docs/ folder structure
  // (Getting Started, Compile a Model, GenAI with LLiMa, Develop Apps, Tools,
  // References) so autodoc-mounted sections stay in sync without hand-listing.
  // A titled doc landing can't lead the tree here (core's "/" is a React page,
  // not a doc, unlike hardware's /hardware), so the lead is an HTML heading.
  docs: [
    {
      type: "html",
      value: "SiMa.ai Neat Documentation",
      className: "sidebar-section-title",
      defaultStyle: true,
    },
    { type: "autogenerated", dirName: "." },
  ],
};

module.exports = sidebars;
